version: '3.8'

services:
  sleep-plus-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Variables de build opcionales
        - VITE_APP_NAME=${VITE_APP_NAME:-Sleep+ Admin}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
        - VITE_ENABLE_DEVTOOLS=${VITE_ENABLE_DEVTOOLS:-false}
        # Usar placeholder para URL din치mica
        - VITE_API_URL=DYNAMIC_API_URL
    container_name: sleep-plus-admin
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOST=0.0.0.0
      # La API_URL se detectar치 autom치ticamente o puede ser configurada
      - API_URL=${API_URL:-}
      # Variables opcionales para diferentes plataformas
      - EASYPANEL_URL=${EASYPANEL_URL:-}
      - RAILWAY_PUBLIC_DOMAIN=${RAILWAY_PUBLIC_DOMAIN:-}
      - RENDER_EXTERNAL_URL=${RENDER_EXTERNAL_URL:-}
    volumes:
      # Montar la base de datos para persistencia
      - ./db.json:/app/db.json
      # Montar archivos de configuraci칩n si es necesario
      - ./server/config.js:/app/server/config.js:ro
    networks:
      - sleep-admin-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:80/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx como proxy reverso (opcional - solo para desarrollo local)
  nginx:
    image: nginx:alpine
    container_name: sleep-plus-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sleep-plus-admin
    networks:
      - sleep-admin-network
    profiles:
      - with-nginx

networks:
  sleep-admin-network:
    driver: bridge

volumes:
  sleep-data:
    driver: local
