version: '3.8'

services:
  sleep-plus-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sleep-plus-admin
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - VITE_API_URL=http://localhost:8080
    volumes:
      # Montar la base de datos para persistencia
      - ./db.json:/app/db.json
      # Montar archivos de configuración
      - ./server/config.js:/app/server/config.js
    networks:
      - sleep-admin-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: sleep-plus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sleep-plus-admin
    networks:
      - sleep-admin-network
    profiles:
      - with-nginx

networks:
  sleep-admin-network:
    driver: bridge

volumes:
  sleep-data:
    driver: local 